import type { ClientReport } from '../reportData';
import { createReportApp } from './app';
import { element } from './dom';
/** This JSON is generated by the typed formatter in the same document, not fetched remotely. */
const report = JSON.parse(element('report-data').textContent) as ClientReport;
const app = createReportApp(report);
app.focus.init();
app.modal.init();
app.sidepanel.init();
app.renderer.init();
